Pie chart
simonmichael/hledger pull request #1467
Opened 2021-01-19 19:27 UTC by raboof

See issue #538

Took https://github.com/NorfairKing/hledger/commits/pie-chart as a starting point

Still to do:
* [ ] don't show a pie chart when viewing a 'leaf' account
* [ ] show 2 pie charts when there are both positive and negative transactions

2021-01-22 16:40 UTC, simonmichael commented
Thanks for reviving this!

`make help-buildtest` shows some make rules that may help show errors like the CI does.

2021-01-22 16:41 UTC, simonmichael commented
Also, screenshots welcome when you get to that point!

2021-01-22 16:46 UTC, raboof commented
Yes, planning to get back to fixing the warnings and adding some more things later ;). Pretty basic for now, but already on par with the existing work I think:

![hledger](https://user-images.githubusercontent.com/131856/105519324-9147ea00-5cd9-11eb-9d23-41fbd988e67c.png)

(snipped out most data for privacy - is there a '3DBenchy for hledger' canonical test dataset somewhere bychance?)

2021-01-22 17:10 UTC, simonmichael commented
Nifty. Is it in addition to/instead of the line chart ?

examples/bcexample.hledger is a pretty good example journal.

2021-01-24 10:22 UTC, raboof commented
That's a lot of taxes! (it's looks like it is showing the USD and the IRAUSD taxes as separate slices, also haven't checked those are converted correctly so the % values make sense)

![pie](https://user-images.githubusercontent.com/131856/105627272-3d064c80-5e36-11eb-8f84-ba2f26b9db7a.png)

2021-01-26 09:37 UTC, raboof commented
showing 2 pie charts when there are both positive and negative transactions might still be a good improvement, but I think this PR is ready to be reviewed even without that.

2021-01-28 01:42 UTC, simonmichael commented
> showing 2 pie charts when there are both positive and negative transactions might still be a good improvement, but I think this PR is ready to be reviewed even without that.

(Thought I replied to this earlier, but I don't see it.) @raboof, won't it potentially show misleading results without that capability ? I think we need it.

2021-01-29 11:00 UTC, raboof commented
> won't it potentially show misleading results without that capability ? I think we need it.

Updated to split the pie chart into positive and negative accounts (only showing them if there is more than one account to show).

The chart would still be confusing when accounts use multiple currencies. I don't think splitting those into multiple pie charts as well would make too much sense - I'm just hiding the pie charts in that case for now.

2021-01-29 15:53 UTC, simonmichael commented
That sounds good. Will review as soon as I clear some PR backlog, thank you! Other reviewers welcome.

2021-02-02 02:28 UTC, simonmichael requested changes
@raboof: I've got this running locally. Great work so far. I'd like to improve usability a bit more if you have time. Do you think some of these could be done:

- Always show both charts, in the same stable positions. When one can't be shown for whatever reason, show it greyed out, or at least some placeholder. 
- Show the charts side by side, to use less vertical space. Negative amounts always on the left, positives on the right I guess.
- In the legend, show the amounts. I know you'll be short of space, maybe the percentage is not necessary there ?

2021-02-02 02:28 UTC, simonmichael commented on hledger-web/hledger-web.cabal
> +    templates/piechart.hamlet
Would you mind making this same change in the package.yaml file, from which this is generated. (Changing the .cabal file as well is optional, stack does it and I sometimes commit that change separately to reduce conflicts.)

2021-02-02 02:36 UTC, simonmichael commented
Also, I have seen it show two pies for one account, but most of the time it shows only one, or none. Perhaps there's a bug ? Eg with examples/sample.journal, a single pie is shown for expenses and for income, and no pies for any other account.

2021-02-02 11:46 UTC, raboof commented
> I'd like to improve usability a bit more (...) Always show both charts, in the same stable positions. When one can't be shown for whatever reason, show it greyed out, or at least some placeholder

Funny, I introduced hiding charts when there is no meaningful data a usability feature, not a shortcoming :D. Happy to adapt though.

> I have seen it show two pies for one particular account, but most of the time it shows only one, or none. Perhaps there's a bug ? Eg with examples/sample.journal, a single pie is shown for expenses and for income, and no pies for any other account.

It shows a pie chart when there is more than one (sub)account being reported on, unless those (sub)accounts contain multiple commodities. That was intentional, but if it creates more confusion than it reduces noise then we should indeed implement a more straightforward behaviour ;).

2021-02-02 14:06 UTC, simonmichael commented
I limited my testing to a single commodity, I'm pretty sure. See if you can reproduce the issue with examples/sample.journal. As a user I'm confused when the pies come and go, especially when I can't see the reason.

2021-02-02 20:03 UTC, raboof commented
> Eg with examples/sample.journal, a single pie is shown for expenses and for income, and no pies for any other account.

This matches what I would expect:
* expenses has 2 subaccounts with a positive balance, so those are shown in a pie chart
* income has 2 subaccounts with a negative balance, so those are shown in a pie chart
* 'assets' has 2 subaccoutns: 1 with negative balance and 1 with positive balance. Since showing a pie chart with just one '100%' category didn't feel very useful to me, I wasn't showing those.
* all other accounts don't have subaccounts, so don't have pie charts

So this was indeed my intended behavior - but evidently that wasn't very intuitive. I'll look into always showing both charts.

2021-02-02 21:22 UTC, simonmichael commented
My idea might not be right either. I just found it confusing as is.

2021-02-08 01:06 UTC, simonmichael commented
Hi @raboof, I just tested your latest push. 

The solid pie charts are a bit clunky of course, but for now, they do reassure that the feature is working..

Any idea why no charts are shown for the sample journal's assets:bank:checking ? http://127.0.0.1:5000/register?q=inacct%3Aassets%3Abank%3Achecking%20

Wouldn't it be more familiar to have the chart for positives on the right, and negatives on the left ?

I wonder how it feels if you show amounts instead of percentages ?

Do you think it's feasible to have some useful info (eg amount) always showing on or near the pie slices themselves ?

2021-02-12 05:16 UTC, Xitian9 commented
I hate to be “that person”, especially when so much great work has been put in here, but I feel compelled to raise the point that it's notoriously difficult for people to be able to [extract accurate information from pie charts](https://scc.ms.unimelb.edu.au/resources-list/data-visualisation-and-exploration/no_pie-charts).

When I generate my financial charts, I use a stacked bar chart with absolute amounts on the left y-axis and percentage of total on the right y-axis for this purpose. It's easier to read, easier to display, and allows you to include both positive and negative amounts in a sensible way.

2021-02-12 08:20 UTC, raboof commented
> Any idea why no charts are shown for the sample journal's `assets:bank:checking`?

(will check when I get back to this)

> Wouldn't it be more familiar to have the chart for positives on the right, and negatives on the left?

Sounds reasonable, will update.

> I wonder how it feels if you show amounts instead of percentages ? Do you think it's feasible to have some useful info (eg amount) always showing on or near the pie slices themselves ?

I think that would be a great idea (though there's something to be said about percentages as well, as they are less likely to invoke 'fear of big numbers' :D ). Perhaps not absolutely necessary for this first iteration though - haven't looked into how hard it would be yet.

> I hate to be “that person”, especially when so much great work has been put in here

Don't worry ;)

> I feel compelled to raise the point that it's notoriously difficult for people to be able to [extract accurate information from pie charts](https://scc.ms.unimelb.edu.au/resources-list/data-visualisation-and-exploration/no_pie-charts).

To be honest I feel like many of those points don't apply so strongly here. Obviously the '3d' pie charts are pure evil. We don't really seem to suffer from any of the '4 signs that your pie is failing', mainly because it's interactive rather than a static image. The 'small percentages' aren't particularly important in our case.
 
> When I generate my financial charts, I use a stacked bar chart with absolute amounts on the left y-axis and percentage of total on the right y-axis for this purpose. It's easier to read, easier to display, and allows you to include both positive and negative amounts in a sensible way.

I would love to have those, and they might indeed replace pie charts. Until we have those, though, I think at least having the pie charts would be a significant improvement over not having them :).

2021-02-17 15:57 UTC, simonmichael commented
Good discussion. @raboof stop me if the below seems not the latest code, I think it is though. I'm testing with `make ghci`, `:main -f examples/sample.journal`.

- I want to see amounts, it's hard to understand what these pies are showing otherwise
- shows 0, 1 or 2 pies for each account, it's hard to understand why
- still showing positives on left, negatives on right
- click assets, move mouse pointer sideways across both pies; one of them is left in highlighted mouseover state
- should this show the subaccounts within the displayed account, or the other accounts being transacted with ?
  Currently it shows the former, but I think people are going to struggle with this. Maybe it should show the other instead,
  or maybe there's some way to make it more obvious what's being shown.

Sorry this is hard to get merged. The UI polish is a big part of the task, and in the present state I'm not sure it adds enough value to release it.

2021-02-17 16:11 UTC, raboof commented
> stop me if the below seems not the latest code, I think it is though

Yeah it is - I should've converted the PR to 'draft' though since I didn't yet find time to pick up some of the comments that I do plan to.

> Sorry this is hard to get merged.

No worries - I only find time to work on this occasionally so that rather drags things out wall-clock-wise, but so far I'm happy with the process.

2021-02-17 16:26 UTC, raboof commented
> should this show the subaccounts within the displayed account, or the other accounts being transacted with ?
Currently it shows the former, but I think people are going to struggle with this. Maybe it should show the other instead,
or maybe there's some way to make it more obvious what's being shown.

My use case is definitely 'subaccounts': I import and auto-classify my banking statements, and then use hledger-web to get a feel for 'where my money is going' (and later I'd like to add budgeting). The pies are nice for that while browsing the 'expenses' tree, like 'x % of my expenses in this period where utilities', with the option to from there 'zoom in' to the individual accounts under 'utilities', etc.

Showing charts of the 'accounts being transacted with' would also *kinda* work: I could open `assets:bank` and see what it transacts with. However, that would lose the hierarchy in the expenses. Also for more complicated journals it would seem browsing the 'expenses' tree hierarchically would make more sense than 'accounts being transacted with'.

2021-02-17 17:03 UTC, simonmichael commented
My guess is people most often are in the account register of their real world bank/credit card accounts. That's where I was, at least, and was getting confused. 

The same information would be available either way, it's just a question of which is shown where. I'd be curious to compare the other way.

2021-02-17 17:14 UTC, raboof commented
> My guess is people most often are in the account register of their real world bank/credit card accounts. That's where I was, at least, and was getting confused.

Interesting, I'm rarely there ;). Perhaps when we show (100%, but labeled) pie charts in more cases this will become less confusing.

> The same information would be available either way, it's just a question of which is shown where

The hierarchy would be different though, right?

2021-02-17 17:20 UTC, simonmichael commented
> The same information would be available either way, it's just a question of which is shown where
> 
> The hierarchy would be different though, right?
> 

You'd see pie charts of assets/liabilities in the revenue/expense account registers, and you'd see pie charts of revenues/expenses in the asset/liability account registers, I assume.

2021-02-17 20:04 UTC, raboof commented
> You'd see pie charts of assets/liabilities in the revenue/expense account registers, and you'd see pie charts of revenues/expenses in the asset/liability account registers, I assume.

Well, yes, but consider the example where you have an 'expense' account 'utilities' broken down in subaccounts 'gas', 'water' and 'electricity' that are paid out of the 'bank' assets account.

If you choose to show pie charts breaking down the 'subaccounts' of the selected account, then when browsing 'expenses' you see how many % of your expenses is 'utilities', and then can 'zoom in' to the 'utilities' account to see this broken down in 'gas', 'water' and 'electricity'.

If you choose to show pie charts breaking down the 'accounts being transacted with', then viewing 'bank' you'll only see *all* the expense accounts in one pie chart. Looking at the expense accounts you'll just see "100% bank". That seems to provide less insight to me. If you have multiple asset accounts then you can now see which asset accounts are used to cover which kinds of expenses, but TBQH that doesn't seem particularly interesting information to me.

2021-05-15 20:41 UTC, simonmichael commented
Does anyone have more thoughts on this ? Here are mine: there are a lot of different needs for charts and different aspects to making them usable and robust. I think we should do the R & D and prototyping outside of hledger-web where possible, eg using separate tools like ploterific (cf my recent discussion with semaj in #hledger and the new https://hledger.org/charting.html), as it's much cheaper to iterate and doesn't commit us prematurely. When we see some charts that seem to have wide usefulness, we can tackle moving them into hledger-web as a separate task.

2021-05-15 20:45 UTC, simonmichael commented
PS and so we can test and compare somewhat realistic examples, perhaps examples/bcexample.hledger will work as a standard data set ?

2021-05-15 22:16 UTC, Xitian9 commented
I can supply a copy of the charts I generate from my hledger files (applied to the bcexample.journal file, modified slightly so that it works and produces nice-looking results), if that's helpful. What is the best way to share images?

2021-05-16 03:08 UTC, simonmichael commented
Yes please.  👍🏻 I guess just drag into the GitHub issue when commenting, probably dragging into an email reply also works. If we're chatting, dragging into Element works similarly, and non-Element can users can try the paste site shortcut in topic - I think it's https://pasteimg.hledger.org

2021-05-16 04:08 UTC, simonmichael commented
> the paste site shortcut in topic - I think it's https://pasteimg.hledger.org <https://pasteimg.hledger.org/>
(No longer in the topic, it's http not https, and now has ads so deprecating this one.

2021-05-16 04:11 UTC, Xitian9 commented
Here is an overall breakdown of expenses and savings; the graph I use to take the place of a pie chart in showing proportion.
![0-breakdown-0](https://user-images.githubusercontent.com/18479956/118385144-e4aac300-b64f-11eb-8e91-f39fb236a504.png)

A graph showing total cashflow in and out over the last year. Amounts are a simple moving average over the previous 14 days.
![1-cashflow-0](https://user-images.githubusercontent.com/18479956/118385145-e5dbf000-b64f-11eb-8c47-07afc8b884e0.png)

Graph of net position, i.e. total assets minus total liabilities.
![2-netposition-0](https://user-images.githubusercontent.com/18479956/118385148-e70d1d00-b64f-11eb-887c-b9b000900173.png)

Graph of net liquid position.
![3-liquid-0](https://user-images.githubusercontent.com/18479956/118385149-e83e4a00-b64f-11eb-82b9-d0511d3c964b.png)

Total assets and liabilities.  Since I haven't bothered separating liquid from non-liquid assets and liabilities, this is similar to the previous graph.
![4-wealth-0](https://user-images.githubusercontent.com/18479956/118385151-e96f7700-b64f-11eb-9ff7-b9a7f3b8fbf4.png)

The next three are graphs of expense categories over the past year, grouped together so the axes aren't too different.
![5-expenses-0](https://user-images.githubusercontent.com/18479956/118385152-ea080d80-b64f-11eb-9ef7-c01e218f0992.png)
![5-expenses-1](https://user-images.githubusercontent.com/18479956/118385154-ebd1d100-b64f-11eb-9ad0-1f6ba55384f3.png)
![5-expenses-2](https://user-images.githubusercontent.com/18479956/118385155-ed9b9480-b64f-11eb-8b15-bd34b12242af.png)

2021-05-16 15:06 UTC, raboof commented
> there are a lot of different needs for charts and different aspects to making them usable and robust.

Sure!

> I think we should do the R & D and prototyping outside of hledger-web where possible, eg using separate tools like ploterific

Can't hurt ;)

> the new https://hledger.org/charting.html

(https://hledger.org/charts.html?)

> When we see some charts that seem to have wide usefulness, we can tackle moving them into hledger-web as a separate task.

I'm personally mainly interested in 'interactively' browsing the data (selecting date ranges and subaccounts). Some graphs might not really be that useful when you have to switch between several tools to see them, but could be useful when integrated into hledger-web - so if we wait for them to "seem to have wide usefullness" outside of hledger-web they might never.

> we can test and compare somewhat realistic examples, perhaps examples/bcexample.hledger will work as a standard data set

I agree a standard example might be helpful. A complication in this particular dataset is that it includes expenses in different currencies (USD and IRAUSD), making them trickier to graph of course - which might be an advantage or a disadvantage depending how you look at it.

Do you have ideas on how to handle multiple currencies in one graph?

> Here is an overall breakdown of expenses and savings; the graph I use to take the place of a pie chart in showing proportion.

This is not bcexample.hledger, right? It's not clear to me why "Food" is split into ''Irregular expenses" and "Regular expenses", how does that work?

2021-05-16 22:01 UTC, Xitian9 commented
> This is not bcexample.hledger, right? It's not clear to me why "Food" is split into ''Irregular expenses" and "Regular expenses", how does that work?

I classify groceries as regular expenses and restaurants and irregular expenses. I grant that this breakdown is specific to me, and it's probably not desirable to apply this widely.

2021-11-21 08:33 UTC, simonmichael commented
What should we do with this PR ?

2021-11-21 13:31 UTC, raboof commented
> What should we do with this PR ?

It's up to you: I still like the feature and am happily using this branch of hledger. Of course I'd hoped it'd be of use to more people than just myself, but I respect that you don't consider it acceptable for inclusion in this state. I don't really see how to make it more attractive, though :). I'm OK with either closing the PR or keeping it open for future suggestions.

2025-05-17 19:33 UTC, simonmichael commented
Hi @raboof. Are you still using this 2021 hledger pr: Pie chart ?

IIRC I felt it needs more refinement to be baked in to hledger-web. If you or anyone would like to rebase it, I'm happy to re-review it.

2025-05-19 08:02 UTC, closed without merging